### PR TITLE
upgrade esprima to 4

### PR DESCRIPTION
**Pull request by oprogramador**

### CODE REVIEW

**Comment by timruffles** [comment]
Thanks! I guess this fixes #1?

**Comment by piotr-s-brainhub** [comment]
yes, it should

**Comment by piotr-s-brainhub** [comment]
@timruffles could you publish new version on NPM?

**Comment by timruffles** [comment]
pushed 1.1

**Comment by timruffles** [comment]
Thanks for your help, have added you as a collaborator!

**Pull request merged**
